services:
  postgres_rdapp:
    build: ./db/postgres
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - rdnetwork
    volumes:
      - rdpgdata:/var/lib/postgresql/data
    hostname: "postgres"
  wildfly_rdapp:
    build: .
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - rdnetwork
    ports:
      - "8080:8080"
      - "9990:9990"
    depends_on:
      - postgres_rdapp
networks:
  rdnetwork:
volumes:
  rdpgdata: